-- Status page schema.

-- Time-series of every probe result (one row per service per region per cycle).
CREATE TABLE IF NOT EXISTS checks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  service_id TEXT NOT NULL,
  region TEXT NOT NULL,
  ok INTEGER NOT NULL,            -- 1 = healthy, 0 = failed
  status_code INTEGER,           -- HTTP status returned (nullable on network error)
  latency_ms INTEGER,            -- request latency in ms (nullable on error)
  error TEXT,                    -- error message when ok = 0
  checked_at INTEGER NOT NULL    -- unix epoch seconds
);

CREATE INDEX IF NOT EXISTS idx_checks_service_time ON checks (service_id, checked_at);
CREATE INDEX IF NOT EXISTS idx_checks_time ON checks (checked_at);
CREATE INDEX IF NOT EXISTS idx_checks_service_region_time ON checks (service_id, region, checked_at);

-- Current aggregated health per service. Drives the banner and alerting.
CREATE TABLE IF NOT EXISTS service_state (
  service_id TEXT PRIMARY KEY,
  current_status TEXT NOT NULL DEFAULT 'unknown', -- available | degraded | down | unknown
  consecutive_failures INTEGER NOT NULL DEFAULT 0,
  last_status_code INTEGER,
  last_latency_ms INTEGER,
  last_changed_at INTEGER,        -- when current_status last changed
  last_alerted_at INTEGER,        -- when we last sent an alert email
  updated_at INTEGER
);

-- Operator-managed (and auto-generated) incidents.
CREATE TABLE IF NOT EXISTS incidents (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT,
  type TEXT NOT NULL DEFAULT 'disruption',   -- info | disruption | outage
  status TEXT NOT NULL DEFAULT 'investigating', -- investigating | identified | monitoring | resolved
  affected_service_ids TEXT,                 -- JSON array of service ids
  auto INTEGER NOT NULL DEFAULT 0,           -- 1 = auto-generated by probes
  started_at INTEGER NOT NULL,
  resolved_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_incidents_started ON incidents (started_at);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents (status);

-- Timeline updates posted to an incident.
CREATE TABLE IF NOT EXISTS incident_updates (
  id TEXT PRIMARY KEY,
  incident_id TEXT NOT NULL,
  body TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  FOREIGN KEY (incident_id) REFERENCES incidents (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_incident_updates_incident ON incident_updates (incident_id, created_at);
